markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: smiler158.github.com
title: 龚小芳的博客
description: JAVA后台,JS前端, Linux, 推荐系统，IOS...
author: xiaofang
email: smiler158#163.com
github: smiler158

config:
  js_dir:
  img_dir:
  css_dir:
